### ISSUE TITLE
[Frontend] Add mask to amount fields

### ISSUE THREAD

**Issue by FelipePSoares** [FelipePSoares/EconoFlow#220]
To make the user life easier, we can add a amount mask to amount fields.

we need to search more, but ng2-currency-mask appears to be a good option.

**Comment by AmirAbdollahi** [comment]
Because of some conflict risks, it's better to start this issue after the changes from issue #256 are merged into the master branch.

**Comment by FelipePSoares** [comment]
good catch, Better wait. and this ticket will be a little bit tricky because you need to change the mask based on user's language.

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares ! is this still open ?

**Comment by FelipePSoares** [comment]
Hi, @saksham-malhotra-27, welcome,

Yes, You can started it if you wanted.

**Comment by saksham-malhotra-27** [comment]
Alright, I'll start with this one

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares , 
I am currently working on implementing the currency mask functionality using the ng2-currency-mask library in the project. Before proceeding further, I wanted to confirm my understanding of the purpose of the mask.
Is the primary goal to:
+ Ensure proper formatting for **currency inputs in the form fields as users type** (e.g., adding commas for thousands and restricting decimal places)?
+ Improve **user experience by visually showcasing** the amount in the correct currency format while users fill in the input fields?
+ The **mask is intended only for the amount entered by the user in input fields**, as there are **already existing function**s (like the ones that **convert numbers to correct currency format**) but no specific masking functionality at the moment.

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares , 
Been working on the same, found this working a bit : 
![image](https://github.com/user-attachments/assets/53f52b87-1635-41bd-bb47-253f01b719d8)

However, there's something else I wanted to bring to your attention. It seems there's an issue here:
![image](https://github.com/user-attachments/assets/700455f6-55ef-4fc9-9f47-5e7add1361f3)

The image shows that the Budget field is set to type "number," but the masking works correctly when the input type is set to "text" and not "number." I've checked Stack Overflow, Medium, and other resources but haven't found any relevant information. Could you help clarify this?

**Comment by FelipePSoares** [comment]
@saksham-malhotra-27 dont worry about that you can change the field to type text.

**Comment by FelipePSoares** [comment]
@saksham-malhotra-27 and the thousand and decimal separators you can pass using variables. To change based on user's language.

**Comment by saksham-malhotra-27** [comment]
Got it! I've changed the budget field to text as per your suggestion.

Here are a few points I want to clarify before proceeding:

1. Validations in Use:
The **currencyValidator** currently supports only the **decimal regex and currency regex**, while the global service separators are set for **en-US** format by default. Here are some screenshots for reference:
+ ![image](https://github.com/user-attachments/assets/0a486001-2a31-41a2-8725-0824ecf15315)
+ ![image](https://github.com/user-attachments/assets/52b1ad20-5c3f-49c2-a554-87e8553074cc)
+ ![image](https://github.com/user-attachments/assets/e055fb42-b540-4c0d-bccf-0f0071beb67c)
Secondly, the values are being stored in decimal format "10000.00" in DB right ? 

2. Handling the Budget Field:
Since the _budget field_ is now a **text** input, I've removed its validators and initialized it with zero (0). I’ve also added checks for _NaN_ to ensure the field processes values correctly:
![image](https://github.com/user-attachments/assets/6b866870-e98c-425c-a46a-80beec44cff1)
The reason for adding _NaN_ checkers is that the reactive form may receive the currency as a string, possibly without commas or decimals. Hence, the _NaN_ checks will help sanitize and process the value properly.

3. Adding Validations:
Do you think I should add any specific validations to the budget field moving forward? Would be great to hear your thoughts on that.

4. Currency Module Variables:
In order to pass variables for thousands and decimal separators in the currency module, I believe I may need to define a function to correctly map the positions of decimals and thousands based on the currency. Do you have any suggestions or pre-existing functions for this in the code? I'd love some guidance on how to handle this properly for different currencies.

**Comment by saksham-malhotra-27** [comment]
No worries @FelipePSoares !  I’m on it today.

**Comment by saksham-malhotra-27** [comment]
Hello, @FelipePSoares!
I’ve implemented the changes you mentioned in the file and also created a dummy page for testing without backend integration (which will be removed when submitting the PR). Below, I’ve included explanations and screenshots to showcase the updates. Let me know if everything looks good or if any adjustments are needed!

### Dummy _**amount**_ field 
I created a dummy version of the amount field to demonstrate the desired behavior:
![Screenshot 2024-12-01 113355](https://github.com/user-attachments/assets/01c317f8-1c59-4b96-8fbf-ea0166de1960)
![Screenshot 2024-12-01 113404](https://github.com/user-attachments/assets/2d55e2dd-83ad-4ca1-842b-93f4c6014353)
![Screenshot 2024-12-01 113424](https://github.com/user-attachments/assets/360b40b1-1e2a-4062-92de-aa3d58232bc1)

If the currency symbol, thousands separator, and decimal separator follow the above format, everything works as expected. Additionally, I’ve included a screenshot to show that the amount value aligns with a raw numerical value, independent of the currency mask.

###  Main File: **_addExpenseComponent_** Changes

1. Fields for Separators
Added fields to handle separators:
![image](https://github.com/user-attaddExpenseComponentachments/assets/d6e3bbac-194d-4ce9-9498-5231263d393a)

2. Initialization
Initialized separator values based on global preferences:
![image](https://github.com/user-attachments/assets/4cbd33fc-1db6-4659-ab36-ec5d815458ce)

3. Validators
Added validators for the input fields:
![image](https://github.com/user-attachments/assets/ffc182cc-b72a-4aec-ad4b-c4ac23575316)

4. Save Function
Updated the save function to parse the currency value into a numerical format. However, since the amount is already the same as its numerical value in text (without masking), do we even need this step here? 
![image](https://github.com/user-attachments/assets/81b07e12-a696-4e75-9bf5-85f4fafce31d)

5. Lastly
I wanted to confirm if the values for groupSeparator and decimalSeparator in main.ts are automatically replaced based on the user's configuration. Is this handled during login or onboarding, or do I need to explicitly call the function first?

Also, just to clarify—groupSeparator refers to the thousands separator, correct? I assumed it means the same based on its naming. Let me know if this understanding is accurate!

**Comment by FelipePSoares** [comment]
Hi @saksham-malhotra-27,

To be honest I don't know that the mask component already return the number without the decimal and group separator, if is this the case I think that don't make sense don't use it. You can just ignore the parseLocaleCurrencyToNumber this was created just to solve the problem that we had before. 

But you are free to choose the solution that you liked more, which you decide I'll agree.

Yes groupSeparator and decimalSeparator are the same thing.
and yes the decimalSeparator and groupSeparator in main.ts are automatically replaced. don't worry about that. This I'm sure that are working well but just for you know, this run everytime that the user access the website, for example, the same user if access using a computer in en-GB will see dot as decimal separator and then if the same user access in a de-DE cellphone will see comma as decimal separator.

**Comment by saksham-malhotra-27** [comment]
Hey @FelipePSoares ! 
The masking part has been fully implemented, and everything is working smoothly on that front. The only thing left to address is the initialization of the amount and budget form controls and some testing.

I’m wondering which approach would be best for initializing these values. Should we initialize the form controls as strings, since we’re using **CurrencyMask** (which handles formatting and returns numeric values on submit), or should we initialize them with numeric values (like 0, which is what **CurrencyMask** returns)?

Both approaches are valid, but I’m leaning towards using strings, as it’s a common practice even when working with **CurrencyMask**. 

Also, do you know if there are any existing tests, or how we can test the frontend code without accessing the backend? Are there any Jest dummy implementations or mock setups for frontend testing that we can use to simulate backend behavior for the tests?

After these I'll send in my PR. 

Thanks!

**Comment by FelipePSoares** [comment]
Hey @saksham-malhotra-27 ,

If you want you can open a DRAFT PR you can see about that [here](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

About the initializing values, you can choose the best approach in your opnion.

I know that exists 2 [unit tests](https://github.com/FelipePSoares/EconoFlow/blob/master/easyfinance.client/src/app/core/utils/pipes/currency-format.pipe.spec.ts) for frontend today but I think that's to simple, but you can get some insights there.

**Comment by saksham-malhotra-27** [comment]
Ah, I see. So, I'm opening a DRAFT PR, and I've already tested those two unit tests. However, as you mentioned, they are too simple for this case.

**Comment by saksham-malhotra-27** [comment]
@FelipePSoares I've submitted the DRAFT PR.

**Comment by saksham-malhotra-27** [comment]
No worries !
