### ISSUE TITLE
Add Project Name to Details Screen

### ISSUE THREAD

**Issue by Dan-613** [FelipePSoares/EconoFlow#223]
Currently, it isn't possible to see which project a user is viewing when looking at the Details screen.
![image](https://github.com/user-attachments/assets/14ef51b9-c2ac-4df0-bde0-f575348a659a)

**Comment by FelipePSoares** [comment]
@Dan-613 This is a really good one. I was planning something like a breadcrumbs with the issue #136, but maybe just the name of project would be enough, what do you think?

**Comment by Dan-613** [comment]
@FelipePSoares I would do both. One is for information display and clarity, the other is for easy navigation.

**Comment by FelipePSoares** [comment]
Perfect.

**Comment by ahmedhalac** [comment]
What is the exact location of the project name and breadcrumbs on the page?

**Comment by FelipePSoares** [comment]
The breadcrumbs is another issue, about the name, I don't know exactly the better place to put it. 

This could be an idea, but I don't know, I don't liked, but I don't know a better place, maybe in the navbar because it's empty, but I was planning put the breadcrumbs there. What do you think that would be better?

![image](https://github.com/user-attachments/assets/01d7f876-9d00-4a79-8517-4f95d6baf116)

**Comment by ahmedhalac** [comment]
I don't think that project name should be contained inside navbar. 
In my opinion the best location would be left from the date picker or above, as shown in the image you sent.

**Comment by ahmedhalac** [comment]
One more question: Why aren't the months in English?

**Comment by FelipePSoares** [comment]
@ahmedhalac maybe the best option could be above the date picker like the image. 

about the months, is in portuguese because my fault. I was configuring the currency and I want to configure to EUR and I put pt-pt as language to configure the currency, but I configure the language of the months also, you can change it to en-GB if you want or I can do that together another issue because it's simple, just need to take take because of the date, could change also.

**Comment by ahmedhalac** [comment]
Okay, I will add project name above the date picker.
