### ISSUE TITLE
UTC Query

### ISSUE THREAD

**Issue by Dan-613** [FelipePSoares/EconoFlow#230]
Is this correct? Converting to UTC? What happens if the user is not UTC-based?

https://github.com/FelipePSoares/EconoFlow/blob/d8f1a576b237725c64026912ff6bbd9b805435db/EasyFinance.Domain/Financial/BaseFinancial.cs#L57

**Comment by FelipePSoares** [comment]
@Dan-613 maybe It's not correct. 
I was having a lot of issues with date because of the time, but the wird thing is I use only date, not the time, I don't care about the time, but it happens exactly because of that, for example I'm +1 hour. If I try to add a expense between midnight to 4am I'll face this problem because the server is on EUA. Because of that I decided to validate everything using UTC and the problem occours just between midnight and 1am and even in the front-end every date is UTC. 

But this don't solve every problem because there is people in a lot of time zones, I need to take a time to work on it and find the best approach.

**Comment by Dan-613** [comment]
I think the only way around that is to ask the user for their timezone and then handle all date validation using that timezone.

For a user in Australia not to be able to enter today's date becuase it's not today in UTC, they would be prevented from using the system.

The alternative is using something like moment.js to handle conversion between local timezone and UTC but I've not properly thought that through yet and might not be possible since we are ignoring the time of day.

**Comment by FelipePSoares** [comment]
Yes, maybe this is the best approach, ask for user in the first login as first and last name. I'm thinking in ask for currency in this screen also, then we can configure application to format all currency in application.

I'll take some time to plan and write issues for this tomorrow.

**Comment by FelipePSoares** [comment]
I got some time today and already created the issues, I'll close this one now. Thank you for you help again.

Issues :
#233
#234
#235
#236
#237
